.\" Process this file with
.\" groff -man -Tascii foo.1
.\"
.TH TSH 1 "OCT 2014" Linux "User Manuals"
.SH NAME
tsh \- Tiny Shell for Operating Systems project
.SH SYNOPSIS
.B ./tsh
.SH DESCRIPTION
.B tsh 
is implemented to try to behave like a normal shell, 
for example, bash. In
.B tsh, we implemented both the basic points and the extra points.
We will try to give the details below.

.IP "Basic Points"

.BR "jobs control"
function is provided in
.B tsh
, such as stopping a foreground process, terminating
a running process, continuing a stopped process, and fetching
a background to foreground. After
.B fork(2)
, we use
.B setpgid(2)
and
.B tcsetpgrp(3)
to setup a process group and foreground process group. We forward
signals like
.B SIGINT
and 
.B SIGTSTP
to the foreground process group. We use
.B sigprocmask(2)
to ignore
.B SIGCHLD
when beginning to process the input commands, and unblock the signal
before waiting for the commands input. When
.B SIGCHLD
is blocked,
.B waitForCmd()
in
.IR runtime.c
will take over the task to reap the child processes. And this is the most
elegant approach to avoid the race condition between waiting for foreground
processes and reaping background processes.

.BR "builtin commands"
can be executed in
.B tsh
because we maintain a builtin commands array in the file 
.IR builtin_cmd.{c|h} .
With this design, we can add new builtin commands easily by
just adding new array elements to the builtin commands array.
And we can also have a common handle process for each builtin
commands.

.IP "Extra Points"

.BR alias/unalias
can help reduce the length of command line we need to
type in the terminal. Before the input commands are 
executed, we preprocess the commands by expanding
them using the alias pair configured by user. By
the way, we not only expand the first argv(argv[0])
but also try to expand the each field in argv.

.BR "I/O redirect"
is implemented in 
.BR tsh
, we could read from files as read from
.B stdin
and write files as write
.B stdout
because this amazing functionality. In
.B tsh
, we implement this function by using a struct named
.B io_config
which specifys the file descriptors to be used as
.B stdin
and 
.B stdout. In fored child processes, we use
.B dup2(2)
to copy the target fds to 
.B stdin(fd=0)
and 
.B stdout(fd=1) before
.B execv(2)
is called.

.BR pipe
is also implemented in
.B tsh. As mentioned in
.B I/O redirect
, 
..B struct io_config
specifies the file descriptors will be used as
.B stdin
and
.B stdout. The file desciptors which used to connect two processes is
generated by the system call
.B pipe(2)
, and pipe[0] will be used as
.B stdin
while pipe[1] will be used as
.B stdout.

.\"SH OPTIONS
.SH BUILTIN COMMANDS
.IP "cd [DIRECTORY]"
Change the current working directory specified as
.B DIRECTORY.
If no argument is provided by user, then this command
will use the home directory of current user by default.
.IP "echo [ARGUMENTS] ..."
This command will print all the provided arguments with
space as delimiter, and finnaly print a new line.
.IP "fg JOB-NUMBER"
.B fg
command take a positive integer argument as job number,
and fetch that background job with the specified job 
number to foreground.
.IP "bg JOB-NUMBER"
.B bg
command take a positive integer argument as job number,
and let that background job with the specified job number
continue running at background status.
.IP jobs
Print all the jobs with different status, such as
Done, Stopped, Running.
.IP "alias [KEY=VALUE]"
Print all the configured alias pari in dictionary order
if no argument is provided. And add the provided key
and value pair to the alias list when provided.

.IP "unalias KEY"
Remove the corresponding key and value pair in the alias list
specified by key.

.\".SH FILES
.\".I /etc/foo.conf
.\".RS
.\"The system wide configuration file. See
.\".BR foo (5)
.\"for further details.
.\".RE
.\".I ~/.foorc
.\".RS
.\"Per user configuration file. See
.\".BR foo (5)
.\"for further details.
.SH ENVIRONMENT
.IP PATH
This environment variable is used by
.IR tsh
to retrieve the external executable file search path.
.\".SH DIAGNOSTICS
.\"The following diagnostics may be issued on stderr:
.\" 
.\"Bad magic number.
.\".RS
.\"The input file does not look like an archive file.
.\".RE
.\"Old style baz segments.
.\".RS
.\".B foo
.\"can only handle new style baz segments. COBOL
.\"object libraries are not supported in this version.
.SH TO BE DONE
.B tsh
doesn't support
.B semicolon(;)
in command line.
.SH AUTHOR
Yang Yang <yangyang2016@u.northwestern.edu>
.\"SH "SEE ALSO"
.\"BR bar (1),
.\"BR foo (5),
.\"BR xyzzy (1)
